version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "axesor-microservice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9xx91yw85hhr"
s3_prefix = "axesor-microservice"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

