AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  axesor-microservice

  Sample SAM Template for axesor-microservice

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CommonSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Role:
      Fn::GetAtt:
        - "LambdaExecutionRole"
        - "Arn"
    Properties:
      Timeout: 9
      CodeUri: axesor/
      Handler: app.commonSearch
      Runtime: nodejs12.x
      Environment:
        Variables:
          AXESOR_API_URL: https://www.axesor.es/buscador-unificado
      Events:
        CommonSearch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /commonSearch
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AxesorApi:
    Description: "API Gateway endpoint URL for Prod stage for CommonSearch function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/axesor/"
  CommonSearchFunction:
    Description: "Axesor common search"
    Value: !GetAtt CommonSearchFunction.Arn
